mytuple = ()
print(mytuple)
mytuple = (1, 2, 3)
print(mytuple)
mytuple = (1, "hello", 3.4)
print(mytuple)
mytuple = ("apple", [8, 4, 6], (1, 2, 3))
print(mytuple)
mytuple = ('p','e', 'r', 'm', 'i', 't')
print(mytuple[0])
print(mytuple[3])
ntuple = ("mouse", [8, 4, 6], (1, 2, 3))
print(ntuple[1][1])
print(ntuple[2][0])
print("sliced :", ntuple[0:3])
for letter in (mytuple):
    print("hello", letter)